### ISSUE TITLE
Build problems

### ISSUE THREAD

**Issue by rbock** [bitbouncer/postgres-asio#1]
When building the library, I am getting:

```
Linking CXX executable ../../../bin/cursor_sample
/usr/bin/ld: cannot find -lcsi-http
/usr/bin/ld: cannot find -lcsi-http-parser
/usr/bin/ld: cannot find -lcsi-avro
/usr/bin/ld: cannot find -lsnappy
/usr/bin/ld: cannot find -lcurl
/usr/bin/ld: cannot find -lcares
/usr/bin/ld: cannot find -lidn
/usr/bin/ld: cannot find -lldap
/usr/bin/ld: cannot find -llber
```

I replaced `${EXT_LIBS}` with `postgres_asio boost_log boost_thread boost_system pthread pq` in the samples/*/CMakeLists.txt for the time being. Compiles fine now.

**Comment by skarlsson** [comment]
thanks,

fixed

2015-12-12 15:56 GMT+01:00 Roland Bock notifications@github.com:

**Comment by rbock** [comment]
Thanks!
